Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: vi-cloudformation-templates
      AccessControl: BucketOwnerFullControl 
      Tags:
        -
          Key: Name
          Value: vi-cloudformation-templates

