name: Terraform
on:
  workflow_dispatch:
  
jobs:
  terraform-create-eks:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run aws-cli
      run: |
         cd learn-terraform-provision-eks-cluster-main
         #terraform destroy -input=false
         terraform init -input=false
         terraform plan -out=tfplan -input=false 
         terraform apply -input=false tfplan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-central-1'
